services:
  auth_api:
    container_name: auth_api
    build:
      context: .
      dockerfile: docker/auth.Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/auth/:/auth
    ports:
      - 8000:8000
    env_file:
      - ./services/auth/.env
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"

volumes:
  postgres_data:
  pgadmin_data: