services:
  account_api:
    container_name: account_api
    build:
      context: .
      dockerfile: docker/account.Dockerfile
    command: poetry run python account/manage.py runserver 0.0.0.0:8082
#    command: sleep infinity
    volumes:
      - ./services/account/accounts/:/home/python_user/account/accounts/
      - ./services/account/django_core/:/home/python_user/account/django_core/
      - ./services/account/utils/:/home/python_user/account/utils/
      - ./services/account/rest_api/:/home/python_user/account/rest_api/
    ports:
      - 8082:8082
    env_file:
      - ./services/account/.env
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"

volumes:
  postgres_data:
  pgadmin_data: