services:
  rest_api:
    build: .
    command: poetry run python app/manage.py runserver 0.0.0.0:8000
#    command: tree
    volumes:
      - ./app/:/server/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - "db:pgsql-server"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    links:
      - "db:pgsql-server"

volumes:
  postgres_data:
  pgadmin_data: