version: '3.9'

services:
  api:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/lms
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - "db:pgsql-server"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8080:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    links:
      - "db:pgsql-server"

volumes:
  postgres_data:
  pgadmin-data:
