# Generated by Django 4.2.4 on 2023-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="answer_file",
            field=models.FileField(
                blank=True, null=True, upload_to="assignment/teacher/answers/"
            ),
        ),
    ]
