# Generated by Django 4.2.4 on 2023-08-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_alter_ftquestionanswer_answer_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="ft_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftquestion_answers",
                to="assignments.ftquestion",
            ),
        ),
    ]
