# Generated by Django 4.2.4 on 2023-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_alter_ftquestionanswer_ft_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ftquestion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memberassignmentftquestion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membertakeassignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
