# Generated by Django 4.2.4 on 2023-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0004_alter_assignment_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberassignmentftquestion",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="membertakeassignment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
