# Generated by Django 4.2.4 on 2023-08-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_alter_memberassignmentftquestion_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftquestionanswer",
            name="accessing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="memberassignmentftquestion",
            name="member_take_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_take_assignment_ftquestions",
                to="assignments.membertakeassignment",
            ),
        ),
    ]
