# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_ftquestionanswer_accessing_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="ftquestion",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="ftquestionanswer",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="memberassignmentftquestion",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="membertakeassignment",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
