# Generated by Django 4.2.4 on 2023-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0007_rename_is_delted_assignment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberassignmentftquestion",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
