# Generated by Django 4.2.4 on 2023-08-19 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("exam_number", models.PositiveSmallIntegerField(editable=False)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.session",
                    ),
                ),
            ],
            options={
                "db_table_comment": "exam for each session of course",
            },
        ),
        migrations.CreateModel(
            name="FTQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="exam/questions/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ftquestions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_ftquestion",
                "db_table_comment": "Each exam can have several file/text type questions. This table stores questions of this type for each exam",
            },
        ),
        migrations.CreateModel(
            name="MemberTakeExam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_visit", models.DateTimeField(auto_now_add=True)),
                ("finish_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_members",
                        to="exams.exam",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.membership",
                    ),
                ),
            ],
            options={
                "db_table": "exams_member_take_exam",
                "db_table_comment": "a table betwen student takes and exam. It shows that the student participated in the exam",
            },
        ),
        migrations.CreateModel(
            name="MemberExamFTQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("answered_text", models.TextField(blank=True, null=True)),
                (
                    "answered_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exam/students/answers/"
                    ),
                ),
                (
                    "ft_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.ftquestion",
                    ),
                ),
                (
                    "member_take_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_take_exam_ftquestions",
                        to="exams.membertakeexam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_member_exam_ftquestion",
                "db_table_comment": "This table stores the student's answer to the exam file/text question",
            },
        ),
        migrations.CreateModel(
            name="FTQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                (
                    "answer_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exam/teacher/answers/"
                    ),
                ),
                (
                    "ft_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ftquestion_answers",
                        to="exams.ftquestion",
                    ),
                ),
            ],
            options={
                "db_table": "exams_ftquestion_answer",
                "db_table_comment": "answer of the file/text type questions",
            },
        ),
        migrations.AddConstraint(
            model_name="membertakeexam",
            constraint=models.UniqueConstraint(
                fields=("exam", "member"), name="unique_exams_member_take_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberexamftquestion",
            constraint=models.UniqueConstraint(
                fields=("member_take_exam", "ft_question"),
                name="unique_exams_member_exam_ftquestion",
            ),
        ),
    ]
