# Generated by Django 4.2.4 on 2023-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_alter_exam_exam_number_alter_exam_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftquestion",
            name="created_datetime",
            field=models.DateTimeField(default="2023-10-10T00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ftquestion",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="exam/questions/"),
        ),
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="answer_file",
            field=models.FileField(upload_to="exam/teacher/answers/"),
        ),
    ]
