# Generated by Django 4.2.4 on 2023-08-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_alter_memberexamftquestion_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberexamftquestion",
            name="ft_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="exams.ftquestion",
            ),
        ),
        migrations.AlterField(
            model_name="membertakeexam",
            name="last_visit",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
