# Generated by Django 4.2.4 on 2023-08-17 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_ftquestion_created_datetime_alter_ftquestion_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberexamftquestion",
            name="send_datetime",
        ),
        migrations.AddField(
            model_name="memberexamftquestion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="memberexamftquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
