# Generated by Django 4.2.4 on 2023-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_memberexamftquestion_ft_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftquestionanswer",
            name="accessing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
