# Generated by Django 4.2.4 on 2023-08-17 13:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_remove_memberexamftquestion_send_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftquestion",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 17, 13, 30, 14, 903367, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ftquestionanswer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ftquestionanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="memberexamftquestion",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membertakeexam",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
