# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_ftquestionanswer_accessing_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="ftquestion",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="ftquestionanswer",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="memberexamftquestion",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="membertakeexam",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
