# Generated by Django 4.2.4 on 2023-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0006_rename_is_delted_exam_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
