# Generated by Django 4.2.4 on 2023-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0006_alter_ftquestion_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftquestion",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ftquestion",
            name="end_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ftquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
