# Generated by Django 4.2.4 on 2023-08-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0008_alter_ftquestion_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="answer_file",
            field=models.FileField(
                blank=True, null=True, upload_to="exam/teacher/answers/"
            ),
        ),
        migrations.AlterField(
            model_name="ftquestionanswer",
            name="ft_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftquestion_answers",
                to="exams.ftquestion",
            ),
        ),
    ]
