# Generated by Django 4.2.4 on 2023-08-18 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0009_alter_ftquestionanswer_answer_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertakeexam",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_exams",
                to="exams.exam",
            ),
        ),
    ]
