# Generated by Django 4.2.4 on 2023-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaids",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-10-10T00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financialaids",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="financialaids",
            name="result",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
