# Generated by Django 4.2.4 on 2023-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaids",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
