# Generated by Django 4.2.4 on 2023-08-19 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialaids",
            name="created_at",
        ),
    ]
