# Generated by Django 4.2.4 on 2023-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0002_financialaids_created_at_financialaids_is_accepted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaids",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
