# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_financialaids_deleted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financialaids",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
