# Generated by Django 4.2 on 2023-05-20 11:17

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.MyUserManager()),
            ],
        ),
    ]
