# Generated by Django 4.2.3 on 2023-07-12 20:23

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="code",
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[accounts.validators.PostalCodeValidator],
            ),
        ),
    ]
