# Generated by Django 4.2.4 on 2023-08-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_number",
                    models.SmallAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("room_title", models.CharField(max_length=300, unique=True)),
                ("capacity", models.PositiveSmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "semester_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Enter the year as follows: 1400-1401", max_length=10
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "First semester"),
                            (2, "Second semester"),
                            (3, "Third semester"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "room_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trs.room"
                    ),
                ),
            ],
            options={
                "db_table": "trs_time_slot",
                "db_table_comment": "The time period depends on the day of the week and the room.",
            },
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("room_number", "day", "start"), name="unique_trs_time_slot"
            ),
        ),
    ]
