# Generated by Django 4.2.4 on 2023-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (0, "Sunday"),
                ]
            ),
        ),
    ]
