# Generated by Django 4.2.4 on 2023-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trs", "0002_alter_timeslot_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ]
            ),
        ),
    ]
