# Generated by Django 4.2.4 on 2023-08-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("group_course_number", models.PositiveSmallIntegerField()),
                (
                    "start_date",
                    models.DateField(help_text="The date of the first session"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="The date of the last session"),
                ),
                (
                    "tuition",
                    models.DecimalField(
                        decimal_places=3, help_text="course tuition", max_digits=14
                    ),
                ),
                (
                    "percentage_required_for_tuition",
                    models.DecimalField(
                        decimal_places=3,
                        default=100,
                        help_text="Tuition percentage required to enter the course",
                        max_digits=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "session_number",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trs.timeslot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "student"),
                            (3, "teacher"),
                            (5, "instructor"),
                            (7, "teaching assistant"),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delted", models.BooleanField(default=False)),
                ("deleted_at", models.BooleanField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_times",
                        to="courses.course",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trs.semester"
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_times",
                        to="trs.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "courses_course_time",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.coursetitle",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="trs.semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("date", "time_slot"), name="unique_session_date_time_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="unique_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetime",
            constraint=models.UniqueConstraint(
                fields=("time_slot", "semester"), name="unique_courses_course_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("course_title", "group_course_number", "semester"),
                name="unique_course",
            ),
        ),
    ]
