# Generated by Django 4.2.4 on 2023-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="group_course_number",
            new_name="course_number",
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("course_title", "course_number", "semester"),
                name="unique_course",
            ),
        ),
    ]
