# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0002_alter_course_deleted_at_alter_coursetime_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="coursetime",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="coursetitle",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
