# Generated by Django 4.2.4 on 2023-08-28 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0003_rename_percentage_required_for_tuition_course_tuition_percentage",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="create_time",
        ),
    ]
