# Generated by Django 4.2.4 on 2023-08-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_course_teacher_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "student"),
                    (3, "teacher"),
                    (5, "instructor"),
                    (7, "teaching assistant"),
                ]
            ),
        ),
    ]
