# Generated by Django 4.2.4 on 2023-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_membership_course_alter_membership_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="unique_membership"
            ),
        ),
    ]
