# Generated by Django 4.2.4 on 2023-08-27 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeacherEducation",
            new_name="Education",
        ),
        migrations.RenameModel(
            old_name="TeacherPublished",
            new_name="Published",
        ),
        migrations.AlterModelTable(
            name="education",
            table="teacher_education",
        ),
        migrations.AlterModelTable(
            name="published",
            table="teacher_published",
        ),
    ]
