# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0002_alter_teacher_deleted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="teachereducation",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="teacherpublished",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
