# Generated by Django 4.2.4 on 2023-08-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
