# Generated by Django 4.2.4 on 2023-08-22 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_alter_content_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="is_delted",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="membervisitcontent",
            old_name="is_delted",
            new_name="is_deleted",
        ),
    ]
