# Generated by Django 5.0.6 on 2024-05-27 08:01

import accounts.authtoken.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "digest",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("token_key", models.CharField(db_index=True, max_length=15)),
                ("last_use", models.DateTimeField(auto_now=True)),
                (
                    "expiry",
                    models.DateTimeField(default=accounts.authtoken.models.expiry_set),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_auth_token",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_token",
            },
        ),
        migrations.CreateModel(
            name="AuthTokenExtra",
            fields=[
                (
                    "authToken",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.authtoken",
                    ),
                ),
                (
                    "ip_address",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="The IP address of user when registered",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", verbose_name="HTTP User Agent"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_auth_token_extra",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_token_extra",
            },
        ),
    ]
